CREATE TABLE CERTIFICATE_TEMPLATE	(	
	CERTIFICATE_TEMPLATE_ID	INTEGER(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TEMPLATE_NAME	VARCHAR(100),
	ISSUER_ID INTEGER(12) not null,
	CERTIFICATE_DESC	VARCHAR(500),
	CREATED_BY INTEGER(12) NOT NULL,
	CREATED_TIME TIMESTAMP NOT NULL,
	MODIFIED_BY INTEGER(12),
	MODIFIED_TIME TIMESTAMP
);