CREATE TABLE CERTIFICATE	(	
	CERTIFICATE_ID	INTEGER(12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CERTIFICATE_NAME	VARCHAR(100),
    CANDIDATE_ID INTEGER(12) NOT NULL,
    ISSUE_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP,
    CERTIFICATE_TEMPLATE_ID INTEGER(12) NOT NULL,
    FILE_PATH VARCHAR(500),
    VERIFICATION_STATUS INTEGER(1),
    VERIFIED_BY_ID INTEGER(12),
    VERIFIED_DATE TIMESTAMP,
	SOCIAL_ACTIVITY_ID INTEGER(12) NOT NULL,
    CREATED_BY INTEGER(12) NOT NULL,
	CREATED_TIME TIMESTAMP NOT NULL,
	MODIFIED_BY INTEGER(12),
	MODIFIED_TIME TIMESTAMP
);

ALTER TABLE CERTIFICATE ADD FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID);
ALTER TABLE CERTIFICATE ADD FOREIGN KEY (SOCIAL_ACTIVITY_ID) REFERENCES SOCIAL_ACTIVITY(SOCIAL_ACTIVITY_ID);
