CREATE TABLE SEQUENCE(
	SEQUENCE_NAME VARCHAR(40) NOT NULL PRIMARY KEY,
	SEQUENCY_VALUE INTEGER(12) NOT NULL DEFAULT 1
);

INSERT INTO SEQUENCE VALUES ('TEST_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('LIKES_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('COMMENTS_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('COMMENTS_REPLY_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('SOCIAL_ACTIVITY_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('ADDRESS_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('CANDIDATE_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('CANDIDATE_PERSONAL_DETAIL_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('CERTIFICATE_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('CERTIFICATE_TEMPLATE_SEQ', 0);
INSERT INTO SEQUENCE VALUES ('USERS_SEQ', 0);

