CREATE TABLE ADDRESS	(
	ADDRESS_ID INTEGER(12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ADDRESS_LINE_1 VARCHAR(500) NOT NULL,
	ADDRESS_LINE_2 VARCHAR(500),
	LANDMARK VARCHAR(100),
	CITY VARCHAR(100) NOT NULL,
	STATE VARCHAR(100) NOT NULL,
	COUNTRY VARCHAR(100) NOT NULL,
	ZIPCODE VARCHAR (20) NOT NULL,
	PHONE INTEGER(12) NOT NULL,
	SECONDARY_PHONE INTEGER(12),
	CREATED_BY INTEGER(12) NOT NULL,
	CREATED_TIME TIMESTAMP NOT NULL,
	MODIFIED_BY INTEGER(12),
	MODIFIED_TIME TIMESTAMP
);