CREATE TABLE CANDIDATE_PERSONAL_DETAIL	(
	PERSONAL_DETAIL_ID INTEGER(12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CANDIDATE_ID	INTEGER(12) NOT NULL,
	FIRST_NAME	VARCHAR(100) NOT NULL,
	MIDDLE_NAME	VARCHAR(100),
	LAST_NAME	VARCHAR(100) NOT NULL,
	DOB DATE,
	EMAIL VARCHAR(100),
	MOBILE_NUMBER INTEGER(15),
	GENDER INTEGER(1),
	MARITAL_STATUS INTEGER(1),
	ADDRESS_ID INTEGER(12),
	CREATED_BY INTEGER(12) NOT NULL,
	CREATED_TIME TIMESTAMP NOT NULL,
	MODIFIED_BY INTEGER(12),
	MODIFIED_TIME TIMESTAMP
);

ALTER TABLE CANDIDATE_PERSONAL_DETAIL ADD FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID);
ALTER TABLE CANDIDATE_PERSONAL_DETAIL ADD FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID);