CREATE TABLE COMMENTS (
	COMMENTS_ID INTEGER(12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	SOCIAL_ACTIVITY_ID INTEGER(12) NOT NULL,
	IS_ACTIVE INTEGER(1) NOT NULL DEFAULT 1,
	COMMENT_TEXT VARCHAR(500),
	CREATED_BY INTEGER(12) NOT NULL,
	CREATED_TIME TIMESTAMP NOT NULL,
	MODIFIED_TIME TIMESTAMP
);

ALTER TABLE COMMENTS ADD FOREIGN KEY (SOCIAL_ACTIVITY_ID) REFERENCES SOCIAL_ACTIVITY(SOCIAL_ACTIVITY_ID);