CREATE TABLE COMMENTS_REPLY (
	COMMENTS_REPLY_ID INTEGER(12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	COMMENTS_ID INTEGER(12) NOT NULL,
	IS_ACTIVE INTEGER(1) NOT NULL DEFAULT 1,
	REPLY_TEXT VARCHAR(500),
	CREATED_BY INTEGER(12) NOT NULL,
	CREATED_TIME TIMESTAMP NOT NULL,
	MODIFIED_TIME TIMESTAMP
);

ALTER TABLE COMMENTS_REPLY ADD FOREIGN KEY (COMMENTS_ID) REFERENCES COMMENTS(COMMENTS_ID);