CREATE TABLE SOCIAL_ACTIVITY (
	SOCIAL_ACTIVITY_ID INTEGER(12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	SOCIAL_ACTIVITY_TYPE INTEGER(1) NOT NULL,
	CREATED_BY INTEGER(12) NOT NULL,
	CREATED_TIME TIMESTAMP NOT NULL
);