CREATE TABLE USER_TYPE (
	USER_TYPE_ID INTEGER(1) PRIMARY KEY NOT NULL,
	USER_TYPE VARCHAR(50) NOT NULL
);

INSERT INTO USER_TYPE VALUES (1, 'CANDIDATE');
INSERT INTO USER_TYPE VALUES (2, 'ISSUER');
INSERT INTO USER_TYPE VALUES (3, 'CLIENT');			