CREATE TABLE USERS (
	USER_ID INTEGER(12) PRIMARY KEY NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	USER_TYPE_ID INTEGER(1) NOT NULL DEFAULT 1,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50),
	HINT_Q VARCHAR(100),
	HINT_A VARCHAR(100),
	EMAIL	VARCHAR(100) NOT NULL,
	MOBILE_NUMBER INTEGER(15),
	ENABLED INTEGER(1) NOT NULL,
	CREATED_BY INTEGER(12) NOT NULL,
	CREATED_TIME TIMESTAMP NOT NULL,
	MODIFIED_BY INTEGER(12),
	MODIFIED_TIME TIMESTAMP
);

			